<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PegawaiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pegawai')->insert([
            [
                'nip' => '198765432001',
                'nama_pegawai' => 'Ahmad Pratama',
                'nik' => '3275010101900001',
                'agama' => 'Islam',
                'jenis_kelamin' => 'Laki-laki',
                'tgl_lahir' => '1990-01-01',
                'tgl_masuk' => '2020-01-15',
                'status_pernikahan' => 'Menikah',
                'no_telp' => '081234567890',
                'email' => 'ahmad.pratama@poliklinik.test',
                'alamat' => 'Jl. Merdeka No. 10, Jakarta',
                'jabatan' => 'Staf',
                'bagian' => 'SDM',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Manajemen',
                'institusi' => 'Universitas Indonesia',
                'thn_lulus' => '2014',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nip' => '198765432002',
                'nama_pegawai' => 'Siti Aisyah',
                'nik' => '3275010202900002',
                'agama' => 'Islam',
                'jenis_kelamin' => 'Perempuan',
                'tgl_lahir' => '1992-02-02',
                'tgl_masuk' => '2021-03-10',
                'status_pernikahan' => 'Belum Menikah',
                'no_telp' => '082345678901',
                'email' => 'siti.aisyah@poliklinik.test',
                'alamat' => 'Jl. Sudirman No. 5, Bandung',
                'jabatan' => 'Asisten Manajer',
                'bagian' => 'Keuangan',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Akuntansi',
                'institusi' => 'Universitas Padjadjaran',
                'thn_lulus' => '2016',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // untuk poliklinik
            [
                'nip' => '001',
                'nama_pegawai' => 'Poliklinik',
                'nik' => '-',
                'agama' => '-',
                'jenis_kelamin' => '-',
                'tgl_lahir' => Carbon::now()->toDateString(),
                'tgl_masuk' => Carbon::now()->toDateString(),
                'status_pernikahan' => '-',
                'no_telp' => '-',
                'email' => '-',
                'alamat' => '-',
                'jabatan' => '-',
                'bagian' => '-',
                'foto' => null,
                'pendidikan_terakhir' => '-',
                'institusi' => '-',
                'thn_lulus' => '-',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // data pensiunan
                'nip' => '198765432003',
                'nama_pegawai' => 'Budi Santoso',
                'nik' => '3275010303900003',
                'agama' => 'Islam',
                'jenis_kelamin' => 'Laki-laki',
                'tgl_lahir' => '1985-03-03',
                'tgl_masuk' => '2010-05-20',
                'status_pernikahan' => 'Menikah',
                'no_telp' => '083456789012',
                'email' => 'budi.santoso@poliklinik.test',
                'alamat' => 'Jl. Gatot Subroto No. 8, Surabaya',
                'jabatan' => '-',
                'bagian' => 'Pensiunan',
                'foto' => null,
                'pendidikan_terakhir' => 'S2 Manajemen',
                'institusi' => 'Institut Teknologi Bandung',
                'thn_lulus' => '2010',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nip' => '198765432004',
                'nama_pegawai' => 'Linda Marlina',
                'nik' => '3275010404900004',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'Perempuan',
                'tgl_lahir' => '1994-04-04',
                'tgl_masuk' => '2022-07-01',
                'status_pernikahan' => 'Belum Menikah',
                'no_telp' => '084567890123',
                'email' => 'linda.marlina@poliklinik.test',
                'alamat' => 'Jl. Ahmad Yani No. 12, Medan',
                'jabatan' => 'Staf',
                'bagian' => 'Administrasi',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Administrasi',
                'institusi' => 'Universitas Sumatera Utara',
                'thn_lulus' => '2018',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nip' => '198765432005',
                'nama_pegawai' => 'Rina Kusuma',
                'nik' => '3275010505900005',
                'agama' => 'Hindu',
                'jenis_kelamin' => 'Perempuan',
                'tgl_lahir' => '1995-05-05',
                'tgl_masuk' => '2023-02-14',
                'status_pernikahan' => 'Belum Menikah',
                'no_telp' => '085678901234',
                'email' => 'rina.kusuma@poliklinik.test',
                'alamat' => 'Jl. Diponegoro No. 20, Yogyakarta',
                'jabatan' => 'Staf',
                'bagian' => 'Pelayanan',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Pelayanan Publik',
                'institusi' => 'Universitas Gadjah Mada',
                'thn_lulus' => '2019',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // untuk bagian = OJT
                'nip' => '198765432006',
                'nama_pegawai' => 'Andi Wijaya',
                'nik' => '3275010606900006',
                'agama' => 'Islam',
                'jenis_kelamin' => 'Laki-laki',
                'tgl_lahir' => '1996-06-06',
                'tgl_masuk' => '2023-06-01',
                'status_pernikahan' => 'Belum Menikah',
                'no_telp' => '086789012345',
                'email' => 'andiwijaya@polilinik.test',
                'alamat' => 'Jl. Pahlawan No. 15, Semarang',
                'jabatan' => 'Staff',
                'bagian' => 'OJT',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Teknik Industri',
                'institusi' => 'Universitas Diponegoro',
                'thn_lulus' => '2022',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                // untuk bagian = Unit Lain
                'nip' => '198765432007',
                'nama_pegawai' => 'Sari Putri',
                'nik' => '3275010707900007',
                'agama' => 'Kristen',
                'jenis_kelamin' => 'Perempuan',
                'tgl_lahir' => '1997-07-07',
                'tgl_masuk' => '2023-05-15',
                'status_pernikahan' => 'Belum Menikah',
                'no_telp' => '087890123456',
                'email' => 'sari123@poliklinik.test',
                'alamat' => 'Jl. Kenangan No. 22, Bali',
                'jabatan' => 'Staff',
                'bagian' => 'Unit Lain',
                'foto' => null,
                'pendidikan_terakhir' => 'S1 Pariwisata',
                'institusi' => 'Universitas Udayana',
                'thn_lulus' => '2021',
                'is_active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]

        ]);
    }
}
